cakes = ["chocolate", "vanilla", "red velvet", "carrot"]
print("The menu currently has the cupcake flavors: " + cakes[0] +", " + cakes[1] + ", "+ cakes[2] + ", and " + cakes[3] + ".")
print("I don't really like " + cakes[2] + " so I'm removing it from the menu.")
del cakes[2]
print("The menu really ought to include lemon cake.")
cakes.append("lemon")
print(cakes)
print("The menu really should also have coffee cake.")
cakes.insert(1, "coffee")
print(cakes)
popped_cake = cakes.pop()
print("Unfortunately, I don't have the ingredients for " + popped_cake + " cupcakes.")
print( "I also think that " +cakes[2] + " might not sell well enough.")
cakes.remove("vanilla")
print("Therefore, my current menu is: ") 
print(cakes)
print("Maybe some more variety would be nice! Let's add in two more flavors.")
cakes.append("apple cinnamon")
cakes.append("pumpkin")
print("Now our current menu is: ")
print(cakes)
too_bitter= "coffee"
cakes.remove(too_bitter)
print(too_bitter.title() + " cupcakes, are just too bitter. So we're removing them from the menu as well.")
print("Now we should try out a couple menu cupcake flavor orders and see which looks best.")
print(cakes)
print(sorted(cakes))
print(sorted(cakes, reverse=True))
cakes.reverse
print(cakes)
print("I think alphabetical makes the most sense.")
cakes.sort()
print("So our final menu will be: ")
print(cakes)